language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-common' ]; then cd .. && eval "mv $currentfolder generator-common" && cd generator-common; fi

